server:
  port: 8081

spring:
  application:
    name: provider-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: lipanre
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mall?serverTimezone=UTC&useSSL=false
    username: root
    password: lipanre
seata:
  tx-service-group: default_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      application: seata-server
      namespace: ${spring.cloud.nacos.discovery.namespace}
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.server-addr}
      data-id: seataServer.properties
      namespace: ${spring.cloud.nacos.discovery.namespace}
      group: SEATA_GROUP
  data-source-proxy-mode: AT

mybatis-plus:
  type-aliases-package: com.lipanre.jvm.stack.cloud.**.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl