server:
  port: 8888
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: lipanre
      config:
        file-extension: yml
    gateway:
      routes:
        - id: provider-route
          uri: lb://provider-service
          predicates:
            - Path=/service-provider/**
          filters:
            - StripPrefix=1

  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}